"""added vector table

Revision ID: a14365378077
Revises: 
Create Date: 2026-06-21 14:41:36.637362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a14365378077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabus_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_prisma_migrations')
    op.alter_column('schedules', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('schedules', 'exam_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('schedules_upload_id_key'), table_name='schedules')
    op.drop_index(op.f('schedules_user_id_idx'), table_name='schedules')
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'schedules', ['upload_id'])
    op.drop_constraint(op.f('schedules_upload_id_fkey'), 'schedules', type_='foreignkey')
    op.drop_constraint(op.f('schedules_user_id_fkey'), 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'uploads', ['upload_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('study_tasks', 'topic_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('study_tasks', 'assigned_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('study_tasks_schedule_id_assigned_date_idx'), table_name='study_tasks')
    op.create_index('idx_schedule_assigned_date', 'study_tasks', ['schedule_id', 'assigned_date'], unique=False)
    op.drop_constraint(op.f('study_tasks_schedule_id_fkey'), 'study_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'study_tasks', 'schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.alter_column('uploads', 'file_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('uploads', 'file_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('uploads', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('uploads_file_hash_idx'), table_name='uploads')
    op.drop_index(op.f('uploads_user_id_idx'), table_name='uploads')
    op.create_index(op.f('ix_uploads_file_hash'), 'uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.drop_constraint(op.f('uploads_user_id_fkey'), 'uploads', type_='foreignkey')
    op.create_foreign_key(None, 'uploads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'clerk_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'stripe_customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'stripe_subscription_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('users_clerk_id_key'), table_name='users')
    op.drop_index(op.f('users_email_key'), table_name='users')
    op.drop_index(op.f('users_stripe_customer_id_key'), table_name='users')
    op.drop_index(op.f('users_stripe_subscription_id_key'), table_name='users')
    op.create_unique_constraint(None, 'users', ['stripe_subscription_id'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    op.create_unique_constraint(None, 'users', ['clerk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('users_stripe_subscription_id_key'), 'users', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('users_stripe_customer_id_key'), 'users', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('users_email_key'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_clerk_id_key'), 'users', ['clerk_id'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'stripe_subscription_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'stripe_customer_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'clerk_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.create_foreign_key(op.f('uploads_user_id_fkey'), 'uploads', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_file_hash'), table_name='uploads')
    op.create_index(op.f('uploads_user_id_idx'), 'uploads', ['user_id'], unique=False)
    op.create_index(op.f('uploads_file_hash_idx'), 'uploads', ['file_hash'], unique=False)
    op.alter_column('uploads', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('uploads', 'file_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('uploads', 'file_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'study_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('study_tasks_schedule_id_fkey'), 'study_tasks', 'schedules', ['schedule_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index('idx_schedule_assigned_date', table_name='study_tasks')
    op.create_index(op.f('study_tasks_schedule_id_assigned_date_idx'), 'study_tasks', ['schedule_id', 'assigned_date'], unique=False)
    op.alter_column('study_tasks', 'assigned_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('study_tasks', 'topic_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key(op.f('schedules_user_id_fkey'), 'schedules', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('schedules_upload_id_fkey'), 'schedules', 'uploads', ['upload_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'schedules', type_='unique')
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.create_index(op.f('schedules_user_id_idx'), 'schedules', ['user_id'], unique=False)
    op.create_index(op.f('schedules_upload_id_key'), 'schedules', ['upload_id'], unique=True)
    op.alter_column('schedules', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('schedules', 'exam_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('schedules', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.drop_table('syllabus_chunks')
    # ### end Alembic commands ###
